<?php

/*
 * @file
 * The install file for the vijo module. 
 * It includes:
 * - Definition of the DB tables
 * - Definition of the basic configuration for vijo
 */

/**
* 
* Implementation of hook_schema().
* @return array  the created schema
*/
function vijo_schema() {
}

/**
 * Implementation of hook_uninstall().
 */
function vijo_uninstall() {
}

/**
 * Implementation of hook_install().
 */
function vijo_install() {
  
}
