<?php

/**
* @file
* The vijo Module.
*
* It allows you to post publications and create new journals based on the ones uploaded to your website..
*/

require_once 'php/vijo.utils.class.php';
require_once 'php/vijo.main.php';

/**
 * Implementation of hook_menu().
 */
function vijo_menu() {

  $items['vijo'] = array(
    'title' => 'ViJo',
    'description' => 'ViJo description',
    'page callback' => 'vijo_page',
    'access arguments' => array('access vijo'),
    // 'access callback' => TRUE,
    'weight' => 30,
    );

  return $items;
}

/**
 * Creates the vijo page
 */
function vijo_page($clear = TRUE) {
  $page = new Utils;
  $main = new MainPage;
  $page->includeMainPageJS();
  $page->includeTestData();
  return $main->getMainPageHTML();
}