vijoData = [
	{authors: ['Daniel Ashbrook', 'Thad Starner'], title: 'Using GPS to learn significant locations and predict movement across multiple users', abstract: 'a a a short abstract that contains few short abstract repetitions'},
	{authors: ['Grant Schindler', 'Christian Metzger', 'Thad Starner'], title: 'A Wearable Interface for Topological Mapping and Localization in Indoor Environments', abstract: 'super nice abstract'},
	{authors: ['Erick Delage', 'Andrew Ng', 'Honglak Lee'], title: 'Automatic Single-Image 3D Reconstructions of Indoor Manhattan World Scenes', abstract: '3d reconstruction from a single image is inherently an ambiguous problem. Yet when we look at a picture, we can often infer 3d information about the scene. Humans perform single-image 3d reconstructions by using a variety of singleimage depth cues, for example, by recognizing objects and surfaces, and reasoning about how these surfaces are connected to each other. In this paper, we focus on the problem of automatic 3d reconstruction of indoor scenes, speci¯cally ones (sometimes called Manhattan worlds") that consist mainly of orthogonal planes. We use a Markov random ¯eld (MRF) model to identify the different planes and edges in the scene, as well as their orientations. Then, an iterative optimization algorithm is applied to infer the most probable position of all the planes, and thereby obtain a 3d reconstruction. Our approach is fully automatic|given an input image, no human intervention is necessary to obtain an approximate 3d reconstruction.'},
	{authors: ['pasjdhfpajsdf', 'jasd'], title: '', abstract: 'a sdf34r asdcasdfer43efc dsc sd'},
	{authors: ['j'], title: 'ajlskdhfa', abstract: ' asdfadsf adsf. asdf. asd.f.asd .a.sdf.asd. asd.'},
	{authors: [''], title: ' asdfl asdfsdf ', abstract: 'asdf ew. fa.d. fds.v.dv.sd.fs.d'},
	{authors: ['asdfasdfasdf'], title: 'dasf asdf adfwemw,e', abstract: 'sd. fa.sdf. a.sdfasdfas.df .adsf.a .sdafsd fasd fadsfads.as. '},
	{authors: ['oiquz4'], title: 'àésd$èdp12p  223e 1peléà.as df23. ', abstract: '.asd f.asdf asdf asdf'},
	{authors: ['lkjshdf', 'asdfasdfasdf', 'hoiwuhouhwoiuhsd', 'ouhweoiuhohd', 'sdfgsdgnewwew'], title: 'asdf a', abstract: 'asd f.adsf.a.dsf.a.sd'},
	{authors: ['sdfs'], title: 'èopk23 e2èo aweke3èfèwejfc', abstract: 'sadfa.sd .asd.f a.sdf .as.df a.df'},
	{authors: ['kjsndlfnnw'], title: 'él,sd,.2.,3e 2,3', abstract: 'asdf.asdf. as.df.asd f.asd.fdd'},
];